/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_hehuidai_binarydemo_MainActivity */

#ifndef _Included_com_hehuidai_binarydemo_MainActivity
#define _Included_com_hehuidai_binarydemo_MainActivity
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_hehuidai_binarydemo_MainActivity
 * Method:    getBinaryBitmap
 * Signature: (Ljava/lang/Object;)V
 */
JNIEXPORT void JNICALL Java_com_hehuidai_binarydemo_MainActivity_getBinaryBitmap
  (JNIEnv *, jobject, jobject);

#ifdef __cplusplus
}
#endif
#endif
